### ISSUE TITLE
class method redefinition

### ISSUE THREAD

**Issue by velkyel** [bamless/jstar#20]
Is it possible redefine class method at runtime?
Something like
```
class A
    fun foo()
        print('foo')
    end
end

A.foo = fun()
    print('bar')
end
```

**Comment by bamless** [comment]
It isn't, and due to some optimizations that are done at class creation time it's unfeasible to implement such a feature. For example: class inheritance uses a copy down approach in order to avoid walking the hierarchy of parents to find inherited methods. This makes method calls faster but it precludes us from redefining the parent class methods (we wouldn't find the new implementation because we already copied  it down during class creation).
 If you need to redefine functions at runtime i would suggest using a list/table of functions.
